### PR TITLE
[Fix #25] Test and fix using serverless

### LINKED ISSUE #25: Test Azure Functions hook server
PR #23 was getting too large, so we will merge it and continue the work here.

To do:
* [ ] Add secrets (do not publish!) and deploy them to Azure Functions.
* [x] Set up GitHub hooks for this repository only, in order to test.
* [x] Test with actual GitHub requests, perhaps it is useful to make `pytest` work.
* [ ] Clean up code that is no longer working.

### PR DESCRIPTION
**Pull request by danuker**
I made sure the `issue_comment` hook works. But there is still the `pull_request_review` hook, so **please request changes from GitHub** (GH won't let me review my own code).

What is removed: **there is no security right now**, seems like the request does not have the client IP. So, the IP allow-list is not enforced. We could use the GitHub webhook secret for this. Should it be done in this PR?

Also, I have not touched the tests. Should I update them in this PR?

The token currently deployed on Azure is from @chevah-robot token. It was deployed via `config.ini` in the [latest uploaded artifact](https://portal.azure.com/#blade/Microsoft_Azure_Storage/ContainerMenuBlade/overview/storageAccountId/%2Fsubscriptions%2Fa98aee2a-9755-4a01-a2bd-aaa61ea1d71d%2FresourceGroups%2Fsls-weur-dev-githubhooks-rg%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fslsweurdev63ba64/path/deployment-artifacts/etag/%220x8D9BFC8B2975D7D%22/defaultEncryptionScope/%24account-encryption-key/denyEncryptionScopeOverride//defaultId//publicAccessVal/None). Tell me if you would prefer to use environment variables which only appear [here](https://portal.azure.com/#@proatria.onmicrosoft.com/resource/subscriptions/a98aee2a-9755-4a01-a2bd-aaa61ea1d71d/resourceGroups/sls-weur-dev-githubhooks-rg/providers/Microsoft.Web/sites/sls-weur-dev-githubhooks/configuration) and not in the filesystem.

reviewers: @adiroiban @ioanacristinamarinescu

### CODE REVIEW

**Comment by danuker** [comment]
another comment

**Comment by danuker** [comment]
needs-review

**Comment by danuker** [comment]
needs-changes

**Comment by danuker** [comment]
changes-approved

**Comment by danuker** [comment]
changes-needed

**Comment by danuker** [comment]
needs-changes

**Comment by danuker** [comment]
needs-review

**Comment by danuker** [comment]
needs-review

**Comment by danuker** [comment]
needs-review

**Comment by danuker** [comment]
Testing with deployed endpoint

changes-approved

**Comment by danuker** [comment]
All right, the hook is now deployed to Azure.

needs-review

**Comment by adiroiban** [comment]
just testing

needs-changes

**Comment by adiroiban** [comment]
needs-review

**Review by adiroiban — CHANGES_REQUESTED** [review]
just testing

**Comment by danuker** [comment]
Looks like the used token does not have enough permissions, for the sftpplus.com repository:

```
Traceback (most recent call last):
  File "/home/site/wwwroot/chevah/github_hooks_server/server.py", line 72, in hook
    response = handle_event(event)
  File "/home/site/wwwroot/chevah/github_hooks_server/server.py", line 131, in handle_event
    return handler.dispatch(event)
  File "/home/site/wwwroot/chevah/github_hooks_server/handler.py", line 47, in dispatch
    return handler(event)
  File "/home/site/wwwroot/chevah/github_hooks_server/handler.py", line 85, in pull_request_review
    self._setApproveChanges(
  File "/home/site/wwwroot/chevah/github_hooks_server/handler.py", line 163, in _setApproveChanges
    issue.edit(assignees=[author_name])
  File "/home/site/wwwroot/.python_packages/lib/site-packages/github3/decorators.py", line 24, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/github3/issues/issue.py", line 236, in edit
    json = self._json(self._patch(self._api, data=dumps(data)), 200)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/github3/models.py", line 153, in _json
    raise exceptions.error_for(response)
github3.exceptions.ForbiddenError: 403 Must have admin rights to Repository.
```

And this is why it could not update the user [in this PR](https://github.com/chevah/sftpplus.com/pull/593).

**Comment by adiroiban** [comment]
> Looks like the used token does not have enough permissions, for the sftpplus.com repository:

can you enable default python output via the logging system so that we can see these errors in azure?

**Comment by danuker** [comment]
> can you enable default python output via the logging system so that we can see these errors in azure?

I can see the log of this error already. You can see it by running the following query [here](https://portal.azure.com/#@proatria.onmicrosoft.com/resource/subscriptions/a98aee2a-9755-4a01-a2bd-aaa61ea1d71d/resourceGroups/sls-weur-dev-githubhooks-rg/providers/Microsoft.Web/sites/sls-weur-dev-githubhooks/appInsightsQueryLogs):

```
traces
| order by timestamp
| where timestamp > datetime(12/17/2021, 12:40:06.847 AM)
| where timestamp < datetime(12/17/2021, 12:40:06.849 AM)
| project timestamp, message, severityLevel
```

**Review by adiroiban — APPROVED** [review]
Thanks.

Let's merge this and fix things is smaller PRs.

**Pull request merged**
